// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
await Firebase.initializeApp(
  options: DefaultFirebaseOptions.currentPlatform,
);
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWWHaq3OrlDN0G_h1NVc1BrPxwA8ZEBAI',
    appId: '1:491559394759:android:e53f64a394d38b369a4de2',
    messagingSenderId: '491559394759',
    projectId: 'nanyang-marche',
    storageBucket: 'nanyang-marche.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHqndAYwSU9bUm02t4_XCVMyMfI7yNhhs',
    appId: '1:491559394759:ios:e1669119318f02a49a4de2',
    messagingSenderId: '491559394759',
    projectId: 'nanyang-marche',
    storageBucket: 'nanyang-marche.appspot.com',
    iosClientId: '491559394759-51eaqibjljl2msa9do7i47so16h2fvdj.apps.googleusercontent.com',
    iosBundleId: 'com.example.backEnd',
  );
}
